version: '3.8'
services:
  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    ports:
      - 5050:5000
    
  checkout-service:
    build:
      context: ./checkout-service
      dockerfile: Dockerfile
    ports:
      - 5051:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  mongodb:
    image: mongo