version: '3.8'
services:
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    # Add any additional configuration for the cart-service

  checkout-service:
    build:
      context: ./checkout-service
      dockerfile: Dockerfile
    # Add any additional configuration for the checkout-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Add any additional configuration for the frontend

  mongodb:
    image: mongo
    # Add any additional configuration for the MongoDB service