### Cart Service

GET http://localhost:5051/api/health


### Email Service 
GET http://localhost:5050/api/health
###
POST http://localhost:5050/api/email/send
Content-Type: application/json

{
    "email": "test@test.com"
}

